name: Build and publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: 'aandoney/auction-svc'
            path: 'src/AuctionService'
          - name: 'aandoney/search-svc'
            path: 'src/SearchService'
          - name: 'aandoney/bid-svc'
            path: 'src/BiddingService'
          - name: 'aandoney/identity-svc'
            path: 'src/IdentityService'
          - name: 'aandoney/gateway-svc'
            path: 'src/GatewayService'
          - name: 'aandoney/notify-svc'
            path: 'src/NotificationService'
          - name: 'aandoney/web-app'
            path: 'frontend/web-app'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
    
    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{matrix.service.path}}/Dockerfile
        push: true
        tags: ${{matrix.service.name}}:latest
